server:
  port: 9091

spring:
  application:
    name: ecomm-backend
  datasource:
    username: root
    password: Suneel@123
    url: jdbc:mysql://localhost:3306/suneel
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  data:
    rest:
      base-path: /api

razorpay:
  key:
    id: 
    secret: 
